# NumPy

<img src="https://numpy.org/doc/stable/_static/numpylogo.svg" alt="NumPy Logo" width="300"/>

NumPy: **Num**erical **Py**thon

Doc: <https://numpy.org/doc/stable/reference/index.html>

`ndarray`: At the core of the NumPy package, is the [`ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

NaN (Not a Number)

## Basic

Reference: <https://numpy.org/doc/stable/user/absolute_beginners.html>

### Indexing and slicing

![indexing and slicing](https://numpy.org/doc/stable/_images/np_indexing.png)

### Basic array operations

1. Ones

    ![ones](https://numpy.org/doc/stable/_images/np_array_dataones.png)

2. Addition

    ![addition](https://numpy.org/doc/stable/_images/np_data_plus_ones.png)

3. Subtraction, multiplication, division

    ![sub mul div](https://numpy.org/doc/stable/_images/np_sub_mult_divide.png)

4. Aggregation

    ![aggregation](https://numpy.org/doc/stable/_images/np_aggregation.png)

### Broadcasting

![multiply](https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png)

![broadcasting 1](https://numpy.org/doc/stable/_images/broadcasting_1.png)

![broadcasting 2](https://numpy.org/doc/stable/_images/broadcasting_2.png)

![broadcasting 3](https://numpy.org/doc/stable/_images/broadcasting_3.png)

![broadcasting 4](https://numpy.org/doc/stable/_images/broadcasting_4.png)

### Matrices

1. Create
    
    ![create](https://numpy.org/doc/stable/_images/np_create_matrix.png)

2. Indexing
    
    ![indexing](https://numpy.org/doc/stable/_images/np_matrix_indexing.png)

3. Aggregation 

    ![aggregation](https://numpy.org/doc/stable/_images/np_matrix_aggregation.png)

4. Axis

    ![axis](https://numpy.org/doc/stable/_images/np_matrix_aggregation_row.png)

5. Addition

    ![addition](https://numpy.org/doc/stable/_images/np_matrix_arithmetic.png)

6. Addition with broadcasting

    ![add with broadcasting](https://numpy.org/doc/stable/_images/np_matrix_broadcasting.png)

7. `ones()`, `zeros()`, `random()`

    ![1d random](https://numpy.org/doc/stable/_images/np_ones_zeros_random.png)

    ![2d random](https://numpy.org/doc/stable/_images/np_ones_zeros_matrix.png)

### Transposing and reshaping a matrix

`arr.reshape()`, `arr.transpose()`, `arr.T`

1. `arr.T`

    ![arr.T](https://numpy.org/doc/stable/_images/np_transposing_reshaping.png)

2. `arr.reshape()`

    ![arr.reshape](https://numpy.org/doc/stable/_images/np_reshape.png)

In [ ]:
import numpy as np

In [21]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("dtype:", arr.dtype)
arr

ndim: 1
shape: (6,)
dtype: float64


array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [22]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [50]:
arr > 0

array([ True, False, False,  True,  True,  True])

In [51]:
arr[arr > 0]

array([ 3.7,  0.5, 12.9, 10.1])

In [52]:
np.where(arr > 0, 2, -2)

array([ 2, -2, -2,  2,  2,  2])

## random

In [45]:
np.random.seed(42)
rng = np.random.default_rng(seed=42)
type(rng)

numpy.random._generator.Generator

In [46]:
rng.integers(low=0, high=10, size=(3, 4))

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]])

In [48]:
rng.standard_normal(size=(3, 4))

array([[-0.31624259, -0.01680116, -0.85304393,  0.87939797],
       [ 0.77779194,  0.0660307 ,  1.12724121,  0.46750934],
       [-0.85929246,  0.36875078, -0.9588826 ,  0.8784503 ]])